@echo off
REM Padiz Daily Automation - Long-form + Shorts
REM Generated by schedule_runner.py
cd /d "C:\youtube_pipeline"
"C:\\Users\\Allah\\AppData\\Local\\Programs\\Python\\Python312\\python.exe" -u schedule_runner.py --today >> "C:\youtube_pipeline\schedule_daily.log" 2>&1
