# -*- coding: utf-8 -*-
"""
Padiz Daily Automation Runner - اجرای روزانه خودکار
=======================================================

این script هر روز دو بار اجرا می‌شود:
  1️⃣  روز فرد (1، 3، 5، ...): فیلم بلند انگلیسی + شورت‌های انگلیسی
  2️⃣  روز زوج (2، 4، 6، ...): فیلم بلند فارسی + شورت‌های فارسی

برای نصب روی Windows Task Scheduler:
  python schedule_runner.py --install
  python schedule_runner.py --install --times 15:30,21:00
  python schedule_runner.py --list
  python schedule_runner.py --remove

کاربری دستی (تست):
  python schedule_runner.py --today      # هر چه امروز باید
  python schedule_runner.py --today --dry-run
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import date

try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except (AttributeError, OSError):
    pass

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TASK_PREFIX = 'PadizDaily'
RUNNER_BAT = os.path.join(BASE_DIR, 'run_padiz_daily.bat')
DEFAULT_TIMES = ['15:30', '21:00']


def _generate_bat(times_list):
    """Windows batch file برای اجرا."""
    base = BASE_DIR.replace('\\', '\\\\')
    python = sys.executable.replace('\\', '\\\\')
    
    content = f"""@echo off
REM Padiz Daily Automation - Long-form + Shorts
REM Generated by schedule_runner.py
cd /d "{BASE_DIR}"
"{python}" -u schedule_runner.py --today >> "{BASE_DIR}\\schedule_daily.log" 2>&1
"""
    return content


def install_schedule(times_list=None):
    """ثبت تسک در Windows Task Scheduler."""
    times_list = times_list or DEFAULT_TIMES
    
    print("[scheduler] ایجاد batch file...")
    with open(RUNNER_BAT, 'w', encoding='utf-8') as f:
        f.write(_generate_bat(times_list))
    
    print(f"[scheduler] ثبت {len(times_list)} تسک در Task Scheduler...")
    
    for i, time_str in enumerate(times_list):
        task_name = f"{TASK_PREFIX}_{i+1}"
        hour, minute = time_str.split(':')
        
        # حذف اگر قبلاً وجود داشت
        subprocess.run(
            ['schtasks', '/delete', '/tn', task_name, '/f'],
            capture_output=True, text=True
        )
        
        # ایجاد تسک جدید
        result = subprocess.run([
            'schtasks', '/create',
            '/tn', task_name,
            '/tr', f'"{RUNNER_BAT}"',
            '/sc', 'daily',
            '/st', f'{hour}:{minute}',
            '/f'
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            print(f"  ✅ {task_name} در {hour}:{minute}")
        else:
            print(f"  ❌ خطا در {task_name}: {result.stderr}")


def list_tasks():
    """نمایش تسک‌های موجود."""
    result = subprocess.run(
        ['schtasks', '/query', '/tn', TASK_PREFIX, '/v'],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(result.stdout)
    else:
        print(f"[scheduler] هیچ تسک {TASK_PREFIX} پیدا نشد")


def remove_schedule():
    """حذف تمام تسک‌های Padiz."""
    print(f"[scheduler] حذف تمام تسک‌های {TASK_PREFIX}...")
    result = subprocess.run(
        ['schtasks', '/query'],
        capture_output=True, text=True
    )
    
    for line in result.stdout.split('\n'):
        if TASK_PREFIX in line:
            task_name = line.split()[0]
            subprocess.run(['schtasks', '/delete', '/tn', task_name, '/f'],
                         capture_output=True)
            print(f"  ✅ حذف: {task_name}")
    
    if os.path.exists(RUNNER_BAT):
        os.remove(RUNNER_BAT)
        print(f"  ✅ حذف: {RUNNER_BAT}")


def run_today(dry_run=False):
    """
    اجرای امروز:
    - روز فرد: انگلیسی (فیلم بلند + شورت‌ها)
    - روز زوج: فارسی (فیلم بلند + شورت‌ها)
    
    حداکثر 5 شورت در روز (owner directive 2026-10-01)
    """
    day_of_month = date.today().day
    is_odd = day_of_month % 2 == 1
    lang = 'en' if is_odd else 'fa'
    
    print(f"[padiz] امروز روز {day_of_month} است (زوج={not is_odd})")
    print(f"[padiz] زبان امروز: {lang}")
    
    if dry_run:
        print("[padiz] (dry-run) اینجا اجرا می‌شود:")
        print(f"  1. فیلم بلند {lang}: python run_long_daily.py --upload --force")
        print(f"  2. شورت‌های {lang} (حداکثر 5): python run_daily.py (x5)")
        return 0
    
    print(f"\n[padiz] 1️⃣  فیلم بلند {lang}...")
    result_long = subprocess.run(
        [sys.executable, 'run_long_daily.py', '--upload', '--force'],
        cwd=BASE_DIR
    )
    
    if result_long.returncode == 0:
        print(f"[padiz] ✅ فیلم بلند موفق")
    else:
        print(f"[padiz] ⚠️  فیلم بلند ناموفق (کد: {result_long.returncode})")
    
    # حداکثر 5 شورت در روز
    MAX_SHORTS = 5
    print(f"\n[padiz] 2️⃣  شورت‌های {lang} (حداکثر {MAX_SHORTS})...")
    
    for i in range(MAX_SHORTS):
        print(f"[padiz]   شورت {i+1}/{MAX_SHORTS}...")
        result_short = subprocess.run(
            [sys.executable, 'run_daily.py'],
            cwd=BASE_DIR
        )
        
        if result_short.returncode != 0:
            print(f"[padiz] ⚠️  شورت {i+1} ناموفق، توقف")
            break
        print(f"[padiz] ✅ شورت {i+1} موفق")
    
    print(f"\n[padiz] ✅ اجرای امروز تمام شد")
    return 0


def main():
    parser = argparse.ArgumentParser(
        description='Padiz Daily Automation Scheduler',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('--install', action='store_true',
                       help='ثبت در Windows Task Scheduler')
    parser.add_argument('--times', default=','.join(DEFAULT_TIMES),
                       help='ساعت‌های اجرا (ویرگول‌جدا شده)')
    parser.add_argument('--list', action='store_true',
                       help='نمایش تسک‌های موجود')
    parser.add_argument('--remove', action='store_true',
                       help='حذف تمام تسک‌ها')
    parser.add_argument('--today', action='store_true',
                       help='اجرای امروز')
    parser.add_argument('--dry-run', action='store_true',
                       help='نشان بده چه می‌شود بدون اجرا')
    
    args = parser.parse_args()
    
    if args.install:
        times_list = [t.strip() for t in args.times.split(',')]
        install_schedule(times_list)
    elif args.list:
        list_tasks()
    elif args.remove:
        remove_schedule()
    elif args.today:
        return run_today(dry_run=args.dry_run)
    else:
        parser.print_help()
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
