# -*- coding: utf-8 -*-
"""Long-form EN topics (16:9, monetization grade). High-RPM niche: money psychology.
Scene = {title, text, speech, image_query}. 22 scenes -> ~9 minutes (>= 8 min for mid-rolls).
"""

LONG_TOPICS_EN = [
    {
        "id": "en_long_money_01",
        "lang": "en",
        "series": "The Psychology of Money",
        "voice_index": 0,
        "music": "cinematic",
        "privacy": "public",
        "title": "10 Money Traps Keeping You Broke (Fix These Now) #money",
        "thumbnail_text": "10 MONEY TRAPS",
        "description": (
            "Most people do not have an income problem - they have a money psychology problem.\n"
            "In this video you will learn the 10 hidden money traps that quietly drain your bank "
            "account every single month, and exactly how to escape each one.\n\n"
            "If you fix even three of these, you will be ahead of 90% of people.\n\n"
            "Padiz Studio publishes deep-dive videos on money, psychology and self-improvement.\n"
        ),
        "cta": "Subscribe for more money psychology deep dives.",
        "tags": ["money", "money psychology", "personal finance", "wealth", "financial freedom",
                 "self improvement", "how to save money", "budgeting", "mindset", "padiz studio"],
        "scenes": [
            {"title": "The Lesson School Never Taught",
             "text": "12 years of school, zero lessons on how money actually works.",
             "image_query": "empty classroom school desks",
             "speech": "For twelve years of school you learned algebra and history, but nobody ever taught you how money actually works. No class on interest, no class on investing, no class on the psychological traps waiting for you the moment you start earning. That single missing lesson is why smart, hard-working people stay broke for life. And over the next few minutes, we will expose every one of them."},
            {"title": "Why Money Traps Work",
             "text": "Your brain values now over later - and every company knows it.",
             "image_query": "brain decision making puzzle",
             "speech": "Before the list, you need to understand why these traps work on almost everyone. Your brain is wired to value now over later. A shiny object today feels real, while retirement feels like a fictional character. Every app, every store, every bank is engineered around that one weakness. Once you see the design behind the traps, they lose most of their power over you."},
            {"title": "Trap 1: Lifestyle Creep",
             "text": "Every raise disappears into a bigger life. Income goes up, savings stay zero.",
             "image_query": "luxury car dealership window",
             "speech": "Trap number one is lifestyle creep. Every time your income goes up, your spending rises to meet it. A bigger car, a nicer apartment, fancier weekends. Ten years of raises later, your bank account looks exactly like it did on day one. The fix is brutal and simple: when your income grows, keep your lifestyle exactly where it was and send the difference straight to savings."},
            {"title": "Trap 2: Paying Yourself Last",
             "text": "Save whatever is left at the end of the month - there is never anything left.",
             "image_query": "piggy bank savings jar coins",
             "speech": "Trap number two is paying yourself last. Most people spend first and then save whatever is left, but there is never anything left. Wealthy people reverse the order. The moment money arrives, a fixed percentage moves to savings and investments, before rent, before coffee, before anything. Then you learn to live on the rest - and somehow, you always do."},
            {"title": "Trap 3: The Minimum Payment",
             "text": "Minimum credit card payments are designed to keep you loyal for decades.",
             "image_query": "credit card payment debt",
             "speech": "Trap number three is the minimum payment. Credit card companies choose that tiny minimum on purpose. Pay only it, and a two thousand dollar debt can cost you five thousand over fifteen years while barely shrinking. The minimum is not a favor - it is the most profitable product they sell. The escape rule is simple: never carry a card balance. Pay it off in full, every single month."},
            {"title": "Trap 4: The Fake Emergency Fund",
             "text": "One broken car without savings becomes three years of debt.",
             "image_query": "broken car repair roadside",
             "speech": "Trap number four is having no real emergency fund. Without at least three months of living expenses saved, life does not wait for payday. One broken transmission, one hospital visit, one job loss becomes debt you carry for years at twenty percent interest. Build that buffer before you invest a single dollar, even if it starts at fifty a month. An emergency fund is not conservative - it is the foundation of every wealthy person you admire."},
            {"title": "Trap 5: Dopamine Shopping",
             "text": "One-click checkout is engineered like a slot machine.",
             "image_query": "online shopping phone credit card",
             "speech": "Trap number five is dopamine shopping. One-click checkout, flash timers and personalized ads are engineered exactly like a slot machine: pull, win, repeat. The excitement lasts twenty minutes; the payment lasts twelve months. Before you buy anything online, wait twenty four hours. If you still want it tomorrow, buy it. Most of the time the craving simply vanishes - and your card thanks you."},
            {"title": "Trap 6: Keeping Up",
             "text": "You compare your real life to everyone else's highlight reel.",
             "image_query": "social media lifestyle phone apps",
             "speech": "Trap number six is keeping up with people you never actually met. You compare your real life - bills, doubts, messy mornings - with somebody else's highlight reel of vacations and new cars, then spend money to win a race that does not exist. Here is the truth: most of those lifestyles are financed by debt. Run your own race, defined by your own numbers, not somebody else's feed."},
            {"title": "Trap 7: Subscriptions",
             "text": "Small monthly charges are the most expensive thing you never notice.",
             "image_query": "remote control couch living room",
             "speech": "Trap number seven is subscriptions. Twelve dollars here, nine dollars there. It feels invisible because no single charge hurts, but add them up and those small charges can quietly drain thousands of dollars a year for services you barely use. The exercise is simple: list every recurring charge you paid last month, then cancel everything you did not use in the last thirty days. That is usually fifty to two hundred dollars a month, back in your account forever."},
            {"title": "Trap 8: No Investor Muscle",
             "text": "Cash loses value every year. Money must work or it slowly dies.",
             "image_query": "stock market chart investing screen",
             "speech": "Trap number eight is never learning to invest. Money sitting in cash loses purchasing power every single year - the same grocery cart costs more every year while your savings quietly shrink. Either your money works for you, or inflation works against you, and there is no third option. You do not need to be an expert. You need an automatic monthly purchase of a broad index fund, started as early as possible, and left alone."},
            {"title": "Trap 9: Emotional Decisions",
             "text": "Fear and greed are the most expensive advisors you will ever hire.",
             "image_query": "worried person finance stress",
             "speech": "Trap number nine is making money decisions emotionally. Buying when everyone is excited and selling when everyone is scared is the single fastest way to transfer your money into somebody else's account. Greed and fear are the most expensive advisors you will ever hire. The antidote is a written rule you follow regardless of feelings: what you buy, how much you buy, and when you sell. Decisions made in calm beat decisions made in chaos, every single time."},
            {"title": "Trap 10: No Written Plan",
             "text": "A financial goal that is not written down is just a wish.",
             "image_query": "writing notebook goal planning desk",
             "speech": "Trap number ten is having no written plan. A financial goal without a number and a deadline is not a goal - it is a wish. Write it down: ten thousand in the bank by December, debt free by June, sixty thousand invested in two years. Numbers with dates become decisions. Wishes stay vague, and vague things never happen. People with written plans do not have better luck; they have better direction."},
            {"title": "Bonus Trap: Golden Handcuffs",
             "text": "A bigger salary can still keep you working until seventy.",
             "image_query": "office worker desk suit tired",
             "speech": "Here is a bonus trap nobody warns you about: golden handcuffs. A fat salary that grows exactly with your expenses keeps you on the treadmill until seventy, because the lifestyle only expands when the income does. The exit is not earning more - it is freezing the lifestyle and letting the gap become freedom. Wealth is not what you earn. Wealth is what you keep, and what keeps working while you sleep."},
            {"title": "Bonus Trap: Financial Denial",
             "text": "Avoiding your bank app does not make the balance bigger.",
             "image_query": "bank statement calculator money",
             "speech": "The second bonus trap is financial denial. Avoiding your bank app, ignoring statements and refusing to check your balances does not make the money grow - it only lets the leaks continue unchecked. Look at your numbers once a week, ten minutes, no judgement. People who face their finances calmly always outperform people who earn more but look away. Awareness alone changes spending behavior within a month."},
            {"title": "The Enough Number",
             "text": "Without a definition of enough, every salary feels like poverty.",
             "image_query": "mountain summit calm sunrise",
             "speech": "Before the fix, one mindset shift: define enough. Without a number that means enough, every salary feels like poverty and every neighbor feels richer than you. Decide what enough actually is - the real number that funds your real life - and suddenly the rat race ends, because you can finally see the finish line. Chasing more forever, without a definition of enough, is the most expensive trap of all."},
            {"title": "30-Day Fix: Automate",
             "text": "Automate 20% before you touch a single bill.",
             "image_query": "automatic transfer banking phone app",
             "speech": "So here is the thirty day fix, step one: automate. Set a transfer for the moment your payment lands - twenty percent if you can, ten percent if that is honest - into an account you do not see and do not spend from. Then build your life around what remains. Automation beats willpower, because willpower is tired on Friday night and motivated only on January first."},
            {"title": "30-Day Fix: Cut and Buffer",
             "text": "Cancel three subscriptions you do not need. Build a three-month buffer.",
             "image_query": "wallet cash money bills",
             "speech": "Step two: cut and buffer. Cancel three subscriptions you did not use in the last thirty days - do it today, not later. Take every cancelled charge and every small win and pour it into a three month emergency buffer until it is full. This is the month the leaks get sealed, because a budget that starts with a decision lasts, and a budget that starts with hope does not."},
            {"title": "30-Day Fix: Invest",
             "text": "Small, automatic, every month - regardless of headlines.",
             "image_query": "coins growing plant investment",
             "speech": "Step three: invest automatically, every single month, no matter how small, and no matter what the headlines scream this week. Consistency is the engine that turns ordinary salaries into extraordinary net worth. You are not trying to get rich in a year; you are building a machine that pays you for decades. Set it up once, then let time and compounding do the heavy lifting while you live your life."},
            {"title": "The High Earner Paradox",
             "text": "Some six-figure salaries end in bankruptcy. Income was never the point.",
             "image_query": "money salary pay slip",
             "speech": "Here is a fact that breaks the myth: people with six figure salaries file for bankruptcy every year. A high income without a system is just a faster car on the same treadmill. The paradox is that earning more can actually make you lazier about the fundamentals, because money always seems to be there - until the month it is not. Income buys you options; only habits decide whether you keep them."},
            {"title": "The Compound Secret",
             "text": "Small amounts, started early, beat big amounts started late.",
             "image_query": "hourglass sand time money",
             "speech": "And here is the reason the whole video matters: compounding. A small amount invested every month starting at twenty-five can beat a much larger amount started at forty, because time does the heavy lifting. That is why the twenty year old with good habits beats the fifty year old with a big salary. Your most valuable asset is not your paycheck - it is the number of years your money has to grow."},
            {"title": "Where This Leaves You in 5 Years",
             "text": "Same income, different life - because the leaks are gone.",
             "image_query": "road horizon open highway future",
             "speech": "Picture where this leaves you in five years. Same salary maybe, but the leaks are sealed, the buffer is full, the investments are compounding quietly in the background. Meanwhile, the version of you who ignored this video is still paying minimums, still chasing sales, still one emergency away from debt. Nothing about your income had to change - only the decisions did. That is the entire difference."},
            {"title": "Your Move This Week",
             "text": "Automate one transfer. Cancel one subscription. Write one number.",
             "image_query": "taking action steps stairs upward",
             "speech": "Your move this week is small: automate one transfer, cancel one subscription, and write one number with a deadline on a piece of paper you will actually see. Three minutes of effort that separates people who stay broke from people who build wealth quietly. If this opened your eyes, subscribe - because the next video goes even deeper into how money really works."},
        ],
    },
]
