# -*- coding: utf-8 -*-
"""English facts pool - global audience. Same format as topics_pool.py."""

FACTS_POOL_EN = [
    {
        'id': 'en_psy_attraction_01',
        'music': 'calm',
        'category': 'Relationship Psychology',
        'voice_index': 1,
        'title': 'Why We Fall for Unavailable People #shorts',
        'description': 'Psychology of attraction!\n\nComment your thoughts!\nPadiz Studio\nhttps://instagram.com/padiz_studio\n\n#shorts #psychology #facts #love #padiz_studio',
        'tags': ['shorts', 'psychology', 'love', 'facts', 'mindset', 'padiz_studio'],
        'slides': [
            {'title': 'The Scarcity Effect',
             'text': 'Your brain values what is hard to get!',
             'speech': 'Psychology shows your brain rates things as more valuable when they are harder to get!'},
            {'title': 'Dopamine Rush',
             'text': 'Uncertainty spikes dopamine to double levels!',
             'speech': 'When you do not know how someone feels, your brain releases twice as much dopamine!'},
            {'title': 'Hidden Competition',
             'text': 'Cold behavior triggers a competition instinct.',
             'speech': 'Cold behavior secretly triggers your competitive instinct to prove your own worth!'},
        ],
    },
    {
        'id': 'en_ocean_01',
        'music': 'chill',
        'category': 'Ocean Mysteries',
        'voice_index': 0,
        'title': '3 Ocean Creatures That Should Not Exist #shorts',
        'description': 'Deep sea monsters!\nPadiz Studio\nhttps://instagram.com/padiz_studio\n\n#shorts #ocean #nature #facts #padiz_studio',
        'tags': ['shorts', 'ocean', 'deepsea', 'animals', 'nature', 'facts', 'padiz_studio'],
        'slides': [
            {'title': 'Immortal Jellyfish',
             'text': 'It can reverse aging and restart life!',
             'speech': 'The immortal jellyfish can reverse its aging and restart its life cycle!'},
            {'title': 'Anglerfish Trap',
             'text': 'It hunts in darkness with a glowing lure!',
             'speech': 'The anglerfish hunts in pitch-black water using a glowing lure!'},
            {'title': 'Shrimp Punch',
             'text': 'Its punch is fast as a bullet!',
             'speech': 'The mantis shrimp punches as fast as a bullet, breaking aquarium glass!'},
        ],
    },
    {
        'id': 'en_space_01',
        'music': 'cinematic',
        'category': 'Space Facts',
        'voice_index': 0,
        'title': '3 Space Facts #shorts',
        'description': 'Space! Padiz Studio #shorts #space #facts',
        'tags': ['shorts', 'space', 'facts', 'padiz_studio'],
        'slides': [
            {'title': 'Long Day', 'text': 'Venus day longer than year!', 'speech': 'On Venus a day lasts longer than its year!'},
            {'title': 'Diamond Rain', 'text': 'Neptune rains diamonds!', 'speech': 'On Neptune it rains diamonds from the sky!'},
            {'title': 'Silence', 'text': 'Space is silent!', 'speech': 'Space is silent because sound needs air!'},
        ],
    },
    {
        'id': 'en_body_01',
        'music': 'chill',
        'category': 'Human Body',
        'voice_index': 1,
        'title': 'Your Body Is Doing THIS Right Now! #shorts',
        'description': 'Insane body facts!\nPadiz Studio\nhttps://instagram.com/padiz_studio\n\n#shorts #health #science #facts #padiz_studio',
        'tags': ['shorts', 'humanbody', 'health', 'science', 'facts', 'padiz_studio'],
        'slides': [
            {'title': '300 to 206 Bones',
             'text': 'Babies have 300 bones, adults 206!',
             'speech': 'Babies are born with 300 bones. Some fuse together, leaving adults with 206!'},
            {'title': 'One-Minute Loop',
             'text': 'Blood circles your body in one minute!',
             'speech': 'Your heart pumps blood through your body in about one minute!'},
            {'title': 'Super Jaw',
             'text': 'Your jaw bites with 200 pounds force!',
             'speech': 'Your jaw muscle can bite down with up to 200 pounds of force!'},
        ],
    },
    {
        'id': 'en_history_01',
        'music': 'cinematic',
        'category': 'Crazy History',
        'voice_index': 0,
        'title': '3 History Facts You Never Learned #shorts',
        'description': 'Wild history!\nPadiz Studio\nhttps://instagram.com/padiz_studio\n\n#shorts #history #facts #learn #padiz_studio',
        'tags': ['shorts', 'history', 'facts', 'learn', 'education', 'padiz_studio'],
        'slides': [
            {'title': 'Cleopatra vs Pyramids',
             'text': 'She lived closer to Moon landing!',
             'speech': 'Cleopatra lived closer to the Moon landing than to the pyramids!'},
            {'title': 'No White House',
             'text': 'Washington never lived in it!',
             'speech': 'Americas first president never set foot in the White House!'},
            {'title': 'Quarter of Earth',
             'text': 'Mongols ruled a quarter of land!',
             'speech': 'At its peak, the Mongol Empire ruled a quarter of all land!'},
        ],
    },
    {
        'id': 'en_sleep_01',
        'music': 'calm',
        'category': 'Sleep and Brain',
        'voice_index': 1,
        'title': 'What 1 Bad Night Does to Your Brain #shorts',
        'description': 'Sleep facts!\nPadiz Studio\nhttps://instagram.com/padiz_studio\n\n#shorts #sleep #brain #health #padiz_studio',
        'tags': ['shorts', 'sleep', 'brain', 'health', 'facts', 'padiz_studio'],
        'slides': [
            {'title': 'Brain Wash',
             'text': 'Sleep flushes toxic waste!',
             'speech': 'While you sleep, your brain washes out toxic waste!'},
            {'title': 'Golden Nap',
             'text': '20 minutes boosts focus fast!',
             'speech': 'A twenty-minute nap boosts energy without grogginess!'},
            {'title': 'Sleepless and Drunk',
             'text': '18 hours awake ruins focus!',
             'speech': 'After eighteen hours awake, your focus crashes dangerously!'},
        ],
    },
    {
        'id': 'en_money_01',
        'music': 'energy',
        'category': 'Money Psychology',
        'voice_index': 0,
        'title': '3 Money Traps Keeping You Poor #shorts',
        'description': 'Money psychology!\nPadiz Studio\nhttps://instagram.com/padiz_studio\n\n#shorts #money #finance #success #padiz_studio',
        'tags': ['shorts', 'money', 'finance', 'success', 'motivation', 'padiz_studio'],
        'slides': [
            {'title': 'Lifestyle Creep',
             'text': 'Raises vanish into spending!',
             'speech': 'Every raise disappears into spending, so savings never grow!'},
            {'title': 'Dopamine Shopping',
             'text': 'Shopping feels good, then regret!',
             'speech': 'Impulse shopping feels rewarding, then regret hits one day later!'},
            {'title': 'Pay Yourself First',
             'text': 'Save before you spend!',
             'speech': 'Wealthy people save first, then spend. Others do the opposite!'},
        ],
    },
    {
        'id': 'en_deep_01',
        'music': 'minimal',
        'category': 'Deep Truths',
        'voice_index': 1,
        'title': 'Why People Suddenly Go Silent... #shorts',
        'description': 'Deep truths.\nPadiz Studio\nhttps://instagram.com/padiz_studio\n\n#shorts #quotes #deep #motivation #padiz_studio',
        'tags': ['shorts', 'quotes', 'deep', 'motivation', 'mindset', 'padiz_studio'],
        'slides': [
            {'title': 'Power of Silence',
             'text': 'Silence becomes peace at last.',
             'speech': 'When explaining changes nothing, silence becomes peace.'},
            {'title': 'Tired of Pretending',
             'text': 'Not lonely, just misunderstood.',
             'speech': 'People are tired of pretending to be okay around those who never understand.'},
            {'title': 'Price of Strength',
             'text': 'Strong today, alone last night.',
             'speech': 'Everyone strong today once survived their darkest night alone.'},
        ],
    },
]
